export const icon = {
  email: require('./email.png'),
  eyeHide: require('./eyeHide.png'),
  eyeShow: require('./eyeShow.png'),
  lock: require('./lock.png'),
  rightArrow: require('./fast-forward.png'),
  apple: require('./apple.png'),
  google: require('./google (1).png'),
  check: require('./checkbox (1).png'),
  uncheck: require('./unchecked (1).png'),
  selected: require('./selected.png'),
  unSelected: require('./unSelected.png'),
  success: require('./success.gif'),
  noData: require('./noData.png'),
};
